- name: create non-root group
  become: true
  group:
    name: "{{ deploy_group }}"
    state: present

- name: create non-root user
  become: true
  user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    shell: "/bin/bash"
    state: present

- name: add authorized_key to non-root user
  become: true
  authorized_key:
    user: "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', '/Users/zkan/Labs/hello-ansible/first_playbook/first_playbook.pub') }}"
