- name: ensure python packages are installed
  become: true
  apt:
    name: ['python3-pip', 'python3-dev', 'fail2ban']
    update_cache: yes

- name: enable SSH within the firewall
  ufw: rule=allow port=22
  become: true

- name: enable firewall itself
  ufw: state=enabled
  become: true
