- name: ensure Nginx is installed
  apt: name=nginx state=present update_cache=yes
  become: true

- name: write custom NGinx configuration
  template: src=nginx_conf.j2
            dest=/etc/nginx/conf.d/app.conf
  become: true
